### ISSUE TITLE
Node8 deprecation for Lambda functions

### ISSUE THREAD

**Issue by antstanley** [dvsa/cvs-svc-technical-records#88]
Hey Folks!

Love that you're working in the open. I've been looking for open source examples of serverless applications, and love that you have put so much of your work public.

Am slightly concerned that all your Node functions are still using Node.js 8. Node 8 is EOL, and due to be fully deprecated by AWS next week. This means you won't be able to update your functions after the deprecation date which is on Monday 3 February.

Runtime support policy: https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

Keep up the working in open. Please update your runtimes 🙏

Ant

**Comment by KHodderDVSA** [comment]
Thanks. I would guess you're basing your comment on the serverless config files, but serverless is being used almost exclusively for offline development rather than deployment. In our deployment pipeline, we have updated all our lambda functions to use the newer versions of node, so we're safe but appreciate the concern. Cheers.
